name: Hello, World!
description: Greet someone and record the time.
author: nipe0324

# Define your inputs here.
inputs:
  who-to-greet:
    description: Whot to greet
    required: true
    default: World

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you.

runs:
  using: node20
  main: dist/index.js
